service: nest-serverless-test

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
